# version: '2.4'

# services:
#   web:
#     image: sanokaji325/new
#     ports:
#       - "80:80"
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     environment:
#       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
#       MYSQL_DATABASE: test_db
#     secrets:
#       - db_root_password
#       - db_user
#       - db_password
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     ports:
#       - "3306:3306"

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     environment:
#       PMA_HOST: db
#       MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
#     ports:
#       - "8080:80"
#     depends_on:
#       - db

# secrets:
#   db_root_password:
#     file: ./secrets/db_root_password
#   db_user:
#     file: ./secrets/db_user
#   db_password:
#     file: ./secrets/db_password

# volumes:
#   db_data:
version: '2.4'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: test_db
    secrets:
      - db_root_password
      - db_user
      - db_password
    volumes:
      - db_data:/var/lib/mysql
      - ./test_db.sql:/docker-entrypoint-initdb.d/test_db.sql
    ports:
      - "3306:3306"

  web:
    image: sanokaji325/new
    ports:
      - "80:80"
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    ports:
      - "8080:80"
    depends_on:
      - db

secrets:
  db_root_password:
    file: ./secrets/db_root_password
  db_user:
    file: ./secrets/db_user
  db_password:
    file: ./secrets/db_password

volumes:
  db_data:

